### PR TITLE
Don't alias Iterator/SubSequence to collection type

### LINKED ISSUE #40: EXC_BAD_ACCESS crash when using SwiftUI's move(fromOffsets:toOffset)
I'm using SwiftUI's [`move(fromOffsets:toOffsets)`](https://developer.apple.com/documentation/swift/mutablecollection/3348325-move) method on `MutableCollection` to move an element in my non-empty array, since it's O(*n* log *n*), whereas if I were to do it manually using `remove(at:)` and `insert(at:)` the operation would be O(*n*^2). However, using it on `NonEmpty` always leads to a crash:

```swift
import NonEmpty
import SwiftUI

var nonEmpty: NonEmptyArray<String> = .init("Hello", "Kenobi...", "there!")

nonEmpty.move(fromOffsets: IndexSet(integer: 1), toOffset: 3) // Thread 1: EXC_BAD_ACCESS (code=2, address=0x16f603fc0)

print(nonEmpty)
```
Using a normal Array works just fine:

```swift
var array: Array<String> = ["Hello", "Kenobi...", "there!"]

array.move(fromOffsets: IndexSet(integer: 1), toOffset: 3)

print(array) // ["Hello", "there!", "Kenobi..."]
```
 Could it be due to some quirk in `NonEmpty`'s [conformance to `MutableCollection`](https://github.com/pointfreeco/swift-nonempty/blob/main/Sources/NonEmpty/NonEmpty.swift#L137-L143)?

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #40.

### CODE REVIEW

File: Sources/NonEmpty/NonEmpty+String.swift [hunk 1]
```diff
@@ -102,7 +102,7 @@ where
       encodedAs targetEncoding: Encoding.Type,
       _ body: (UnsafePointer<Encoding.CodeUnit>) throws -> Result
     ) rethrows -> Result where Encoding: _UnicodeEncoding {
-      try self.withCString(encodedAs: targetEncoding, body)
+      try self.rawValue.withCString(encodedAs: targetEncoding, body)
```
Comment (stephencelis) [inline Sources/NonEmpty/NonEmpty+String.swift:105]: Unrelated fix. We had a warning that this was a recursive call 😬

File: Sources/NonEmpty/NonEmpty.swift [hunk 2]
```diff
@@ -2,8 +2,6 @@
 public struct NonEmpty<Collection: Swift.Collection>: Swift.Collection {
   public typealias Element = Collection.Element
   public typealias Index = Collection.Index
-  public typealias Iterator = Collection.Iterator
-  public typealias SubSequence = Collection.SubSequence
```
Comment (stephencelis) [inline Sources/NonEmpty/NonEmpty.swift:6]: It seems it was a mistake to proxy the iterator and subsequence types through, and made mutations potentially unsafe, like in #40.

**Review by mbrandonw — APPROVED** [review]
